### ISSUE TITLE
Does not deploy

### ISSUE THREAD

**Issue by rnhassan** [projectkudu/SimpleWAWS#10]
Hi,

I downloaded CRM Android client application. I am using VS 2015. The solution builds, but does not deploy. The odd thing about it is that the error list is empty. It is impossible to troubleshoot without getting feedback. Did anyone else face this issue before?

**Comment by lindydonna** [comment]
It looks like the Debug and Release configurations don't have "Deploy" selected for the Android project. To fix, go to Build -> Configuration Manager and check "Deploy" for the project XamarinCRM.Android.

**Comment by rnhassan** [comment]
Donna,

Thanks for your reply. Donna, I have the build configuration set to Deploy; when I run it, whether I am trying to use the simulator, or a connected phone, I get an error, but the error list is empty !!. I will use another machine to build and deploy and see if I get the same issue there.

Thanks again.

**Comment by lindydonna** [comment]
What is in your error log?  Are you using Visual Studio or Xamarin Studio?

**Comment by rnhassan** [comment]
Donna,

I have both, but I only tried it on VS 2015. That is the thing, the error list is empty !! when I run the application, the Output indicates that the build is successful, but the deploy failed and then opens the error list, which comes up empty. Any other error logs I need to examine?

**Comment by lindydonna** [comment]
Try turning on verbose logging in your build settings in Visual Studio. You need to look at the full text in the output window--the error window usually doesn't show these errors.

**Comment by rnhassan** [comment]
Donna,

I got a fresh download from tryappservice.azure.com, compiled the app and tried to run it. I got a message that there were build errors... chose to break, then the following Error List opened.
![errorlist](https://cloud.githubusercontent.com/assets/3901493/12689710/3709e24e-c6a4-11e5-945c-8f024a77f983.PNG). Here is a snapshot of the build output. 
![buildoutput](https://cloud.githubusercontent.com/assets/3901493/12689748/6ab1c670-c6a4-11e5-9639-163af9b2b648.PNG)

**Comment by rnhassan** [comment]
Donna,

The application deploys now. All I had to do was Sign out of my Xamarin account, and login again... beats me why was that needed, but I decided to give it a shot since the Output mentioned "Bundling assemblies requires a Enterprise license."

Thanks a lot for your help.
