### ISSUE TITLE
jsclient not responding

### ISSUE THREAD

**Issue by pz7gc3** [projectkudu/SimpleWAWS#13]
I just decided to do the https://tryappservice.azure.com/en-us tutorial. I dowloaded the native iOS and played around using the iPhone simulator. I wanted to see if the data that I entered into the app would be available if accessed from another device. I tried to go to https://f264c34c-0ee0-4-231-b9ee.azurewebsites.net/jsclient/ where the guid obviously is my "try-it-out" id. The jslient page loaded but it is not getting any data. This is what the page looks like:

<img width="802" alt="testing_jsclient" src="https://cloud.githubusercontent.com/assets/313500/12693829/a1900a4a-c720-11e5-844a-d6ffcf870e5f.png">

Regards,

Johan Sundström

**Comment by lindydonna** [comment]
The JS client had an issue and we've currently removed it from Try App Service. We'll add it back soon.
