### ISSUE TITLE
Why don't your "try a mobile app" templates allow for Visual Studio?

### ISSUE THREAD

**Issue by actuary21c** [projectkudu/SimpleWAWS#20]
I've just tried your "try creating a mobile app" at https://tryappservice.azure.com/en-us , but all the templates seem to need me to install some prequisites (eg Xamarin or Xcode) that I don't want to have! I already use Visual Studio 2015, so why should I have to install something else?  Why haven't you got a simple example that will work with Visual Studio?

**Comment by lindydonna** [comment]
The Windows versions don't require anything else. Does it show the requirement?  If so, we have a bug in the UI.

**Comment by lindydonna** [comment]
I just checked the template, and the Windows options do not require anything other than Visual Studio.

**Comment by actuary21c** [comment]
Thanks lindydonna, but I don't think what you are saying is correct. When I choose to create a Mobile App in Step 1, if you choose CRM app or Field Engineer in step 2, it then comes up (eg for CRM) with "Prerequisite: install Xamarin Studio for Windows or OS X" and "Download the Xamarin iOS client app:

see screenshot at https://patrickjlee.smugmug.com/Other/Miscellaneous/i-ctHX2Q4/A

Maybe you are saying that *if* you choose the ToDo template in Step 2, then there are Windows options which don't require anything other than Visual Studio (NB it seems to say 2015 Update 2 is required)?

**Comment by lindydonna** [comment]
The Field Engineer and Xamarin CRM templates use Xamarin, but they are more full-featured.  Your issue asked for a simple sample that works on just VS, which is the todo sample.

The prerequisite technically its VS 2013 or higher, but we wanted to link to the latest. We can adjust the wording to make it more clear.

**Comment by actuary21c** [comment]
OK thanks, I'll try out the todo sample

**Comment by actuary21c** [comment]
I tried it and contrary to what you said, there were loads of prerequisites needed: I had to install stuff for windows phone (which I'm not interested in, again why haven't you made a simple demo that can just have a simple html or console app or WPF client??), and then it still wouldn't work (I got exceptions when running in debug mode).  So I tried installing Visual Studio 2015 Update 2 (I was on Update 1) hoping that would solve the problem, but it didn't:
I get an exception again while running in debug mode:
"HttpRequestException was unhandled by user code" on the following line in OnNavigatedTo in TryMobileApp.MainPage:
await RefreshToDoItems(); 

And (probably because of that) if I run without debugging, the app displays for a few seconds then silently closes ...

**Comment by lindydonna** [comment]
Did all of this take more than one hour? If so, your site probably expired and you need to create a new one. 

Previous installs of VS included phone tools by default, so we didn't call it out. However, you can always load just the Windows Store or UWP solution. 

We don't have a console app or WFP app because those aren't mobile clients and half of the functionality of the product does not work (auth and push). The JavaScript client will be added back soon. 

Would you mind sharing why it was surprising that you need mobile client tools to try out a mobile app product? Do you plan to only work on the backend and someone else would write the move client?

**Comment by actuary21c** [comment]
Thanks, yes, it did take more than one hour (in fact about 3 hours, with 2 restarts!) to installed Visual Studio 2015 Update 2, so that is probably why the app crashed (shouldn't it have at least some basic error trapping to catch this exception and give the user a meaningful message, given that this must happen quite often - ie I had Visual Studio 2015 Prof Update 1, and many clients will have an older version).
After starting again, and downloading the Windows client app again, it works, but only partially: if I went offline, the app crashed again.

I agree that I should not have been surprised that I would need mobile client tools to try out the mobile app product - presumably these are needed to manage the local copy of the data while the app is offline?

**Comment by lindydonna** [comment]
If you want the app to work offline, you can follow this tutorial: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-windows-store-dotnet-get-started-offline-data/. This requires that you install a VSIX package for SQLite, and we wanted to make the process as simple as possible. 

The mobile client tools are needed if you want to actually do development on the mobile client itself. The Todo list sample is the same as we use in the sample that's provided in the product, and our tutorials have you make code changes (like the tutorial I mentioned above). Without the tools, you can't actually customize the mobile app in any way.

**Comment by actuary21c** [comment]
ok, thanks, that makes sense now :)

**Comment by actuary21c** [comment]
Presumably the app service can still be queried via its WebApi if one knows its url?

**Comment by lindydonna** [comment]
Btw, the Win 8.1 project works fine in VS 2013, I just tried it. The UWP project requires VS 2015 on Win10 because that is a prerequisite of the tools themselves.

**Comment by lindydonna** [comment]
Yes, the service can be queried with a REST client. For instance, do a GET on yourappname.azurewebsites.net/tables/TodoItem.

**Comment by actuary21c** [comment]
Thanks - so from a web browser (because of https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-client-and-server-versioning/#2.0.0) I need to specify the ZUMO-API-VERSION) eg  yourappname.azurewebsites.net/tables/TodoItem?ZUMO-API-VERSION=2.0.0

**Comment by lindydonna** [comment]
That's right.

**Comment by actuary21c** [comment]
Many thanks, I think I've now got a handle on this and can take things further :+1:
