### ISSUE TITLE
Error when opening the iOS app

### ISSUE THREAD

**Issue by liamartinez** [projectkudu/SimpleWAWS#4]
Hi, 

I can't open the iOS app -- getting this error:
"TryMobileApp.xcodeproj cannot be opened because the project file cannot be parsed."
I've tried opening it with Xcode 6 and 7(beta). 

Has anyone seen this error before? Thanks!

**Comment by davidebbo** [comment]
@liamartinez there does appear to be an issue. We are investigating.

**Comment by davidebbo** [comment]
@liamartinez issue should be fixed now. Would you mind giving it another try? Thanks for reporting the problem!
