### ISSUE TITLE
resource loading is very slow

### ISSUE THREAD

**Issue by ahmelsayed** [projectkudu/SimpleWAWS#43]
this might be related to #41

**Comment by fashaikh** [comment]
Yes . Will move [this ](https://github.com/projectkudu/SimpleWAWS/blob/master/SimpleWAWS/Global.asax.cs#L130)to a background operation 
Shoudl also solve #41

**Comment by ahmelsayed** [comment]
what is that line doing there in the first place?

**Comment by fashaikh** [comment]
Without it I didnt see the resources getting loaded unless /resource was called. I'll check again

**Comment by fashaikh** [comment]
Fixed with 619987b  . The long load time was likely  due to the duplicate empty resourcegroups  that had been created. The last app restart took `18 seconds` for the freesites to show up
