### ISSUE TITLE
Runtime error in your App Services trial

### ISSUE THREAD

**Issue by pcwproduction** [projectkudu/SimpleWAWS#48]
Your free trial of the Azure App Services has a runtime error.  I tried it.  Got to a search screen and entered the suggested 'park' and got a runtime error.

https://36081628-0ee0-4-231-b9ee.azurewebsites.net/search.cshtml

**Comment by fashaikh** [comment]
Can you try now? I've patched the site which was missing a couple of appsettings. Investigating why this happened. 
https://36081628-0ee0-4-231-b9ee.azurewebsites.net/search.cshtml?q=park

**Comment by fashaikh** [comment]
Thank you for reporting this @pcwproduction ! 
Its fixed now. e.g: https://c3721110-0ee0-4-231-b9ee.azurewebsites.net/search.cshtml?q=park
